# EE 160 Team AMERICA Road Trip Final Project Makefile


all:

RoadTrip: pathplanning.o parser.o RoadTrip.c

pathplanning.o: pathplanning.h

parser.o: parser.h

# clean targets

.PHONY: clean build-clean

clean: build-clean

build-clean:
	-rm *.o
